상품 상세 정보
wecode-bootcamp-korea/34-1st-Wesop-backend pull request #12
Opened 2022-06-28 01:08 UTC by jiminnote

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 상세 정보

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
category_id 에 해당하는 상품정보 get

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
* Q함수 (or 조건걸기)

2022-06-28 01:43 UTC, lordmyshepherd requested changes

2022-06-28 01:43 UTC, lordmyshepherd commented on product/views.py
> +                } for product in products]
카테고리 정보를 상품 객체 안으로 옮기는게 좋겠습니다.

피드백1. 상품 리스트로 반복문으로 돌면서, category_id, category_name에 계속해서 값을 업데이트해주고 있습니다.
피드백2. 상품 정보를 요청했으면 최상위 객체가 상품 정보가 되어야 합니다.

아래와 같은 구조로 수정해주세요.
```suggestion
            result = [
                {
                "products"           : 
                    {
                        "product_id"     : product.id,
                        "product_name"   : product.name,
                        "category_id"        : product.category.id,
                        "category_name"      : product.category.name,
                        "product_detail" : [
                            {
                                "product_option_id" : product_option.id,
                                "size_mL"           : product_option.sizes_mL,
                                "price"             : product_option.price,
                                "image_url"         : product_option.image_url,
                            } for product_option in product.productoption_set.all()
                        ],
                        "product_feature" : [
                        {
                            "feature" : feature.feature.name,
                            "content" : feature.content
                            }for feature in product.Products_feature.filter(is_addtional=False)
                        ]
                        }
                } for product in products]
```

2022-06-28 01:43 UTC, lordmyshepherd commented on product/views.py
> +
KeyError와 Category.DoesNotExist error는 언제 발생하나요?
```suggestion
        except KeyError:
            return JsonResponse({"message" : "KEY_ERROR"}, status = 400)
        
        except Category.DoesNotExist:
            return JsonResponse({"message" : "NO_CATEGORY_FOUND"}, status = 400)
        
        
        
```

2022-06-29 02:08 UTC, Kang-kyunghun requested changes

2022-06-29 02:08 UTC, Kang-kyunghun commented on wesop/urls.py
> +    path('product',include('product.urls'))
```suggestion
    path('products',include('product.urls'))
```

2022-06-29 05:53 UTC, merged